PSS/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',views.Index.as_view(),name = 'index'),
]

accounts/urls.py
from django.urls import path,include
from accounts import views
from django.contrib.auth.views import LoginView, LogoutView





app_name = 'accounts'


urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('login/',LoginView.as_view(template_name = 'accounts/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('change_password_user=<slug:slug>/',views.ChangePasswordView,name = 'change_password'),
    path('forgot_password/',views.ForgotPasswordView,name = 'forgot_password'),
    path('success/',views.SuccessView.as_view(),name = 'success'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class UserModel(AbstractUser):
    Firstname = models.CharField(max_length=50, null=False, blank=False, default="")
    Lastname = models.CharField(max_length=50, null=False, blank=False, default="")
    Birth = models.CharField(max_length=256,null=True, blank=True)
    Info = models.CharField(max_length=255, null=False, blank=True, default="")
    Job = models.CharField(max_length=50, null=False, blank=True, default="")
    ProfilePicture = models.ImageField(max_length=255, default='static\profile\assets\img\default_original_profile_pic.png', upload_to='profile\assets\img')
    CoverPicture = models.ImageField(max_length=255,default='static\profile\assets\img\need_cover.jpg')
    
    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.forms import UserCreationForm
from accounts import models
from django.conf import settings

from django.core import validators 



    
    


class UserForm(UserCreationForm):
    '''
    password = forms.CharField(widget = forms.PasswordInput())
    password_confirm = forms.CharField(widget = forms.PasswordInput())

    terms = forms.BooleanField(
    error_messages={'required': 'You must accept the terms and conditions'},
    )

    def clean(value):
        all_clean_data = super().clean()
        n1 = all_clean_data['password']
        n2 = all_clean_data['password_confirm']
        if n1 != n2:
            raise forms.ValidationError("passwords don't match")
     '''

    terms = forms.BooleanField(
    error_messages={'required': 'You must accept terms and conditions'},
    )

    class Meta():
        model = models.UserModel
        fields = ('username','email','password1','password2','Firstname','Lastname','Birth')
        widgets = {
            'Birth':forms.TextInput(attrs={'class':'datepicker'}),
            }


class ChangePasswordForm(forms.Form):
    confirmation_code = forms.CharField(max_length = 200)
    new_password = forms.CharField(widget = forms.PasswordInput())
    new_password_confirm = forms.CharField(widget = forms.PasswordInput())

    def clean(value):
        all_clean_data = super().clean()
        n1 = all_clean_data['new_password']
        n2 = all_clean_data['new_password_confirm']
        if n1 != n2:
            raise forms.ValidationError("passwords don't match")


class ConfirmationCodeForm(forms.Form):
    username = forms.CharField()

PSS/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.


class Index(generic.TemplateView):

    template_name = 'index.html'

accounts/views.py
from django.shortcuts import render, redirect
from accounts import models, forms
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import CreateView, UpdateView, TemplateView
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
import random
from django.core.mail import send_mail
from django.contrib.auth.password_validation import validate_password, MinimumLengthValidator

#used for recatcha
import json
import urllib
from django.contrib import messages






# Create your views here.



class SignUpView(CreateView):
    model = models.UserModel
    
    form_class = forms.UserForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'


    
    form_invalid_message = 'لطفا فیلد من ربات نیستم را کامل کنید'
    def form_valid(self, form):

        recaptcha_response = self.request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
            'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
            'response': recaptcha_response
        }
        data = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=data)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        ''' End reCAPTCHA validation '''
        
        if result['success']:
            form.save()
            messages.success(self.request, 'New comment added with success!')

            return super(SignUpView, self).form_valid(form)
        else:
            
            messages.error(self.request, self.form_invalid_message)
            return super().form_invalid(form)


    def form_invalid(self, form):
        messages.error(self.request, self.form_invalid_message)
        return super(SignUpView, self).form_invalid(form)






def ForgotPasswordView(request):
    if request.method == 'POST':
        data = request.POST.copy()
        form = forms.ConfirmationCodeForm(data=request.POST)

        if form.is_valid():
            username = data.get('username')
            try :
                user = models.UserModel.objects.get(username__exact=username)
                if user is not None:
                    var = 'abcdefghijklmnopqrstuvwxyzABCDEFIJKLMNOPQRSTUVWXYZ1234567890'
                    confirmationcode=''
                    for i in range(0,random.randrange(10,13,1)):
                        c = random.choice(var)
                        confirmationcode += c
                 
                    send_mail(
                    'کد تایید',
                    '''کد تایید برای تغییر کلمه عبور شما عبارت است از
                    {confirmation_code}'''.format(confirmation_code = confirmationcode),
                    'alienone306@gmail.com',
                    [user.email,],
                    fail_silently=False,
                    )

                    user.set_password(confirmationcode)
                    user.save()
                    return redirect("accounts:change_password",slug = username)
            except:
                error = 'نام کاربری وارد شده اشتباه است'
                return render(request,'accounts/rp_1.html',{'form':form,'error':error})
          
    else:
        form = forms.ConfirmationCodeForm()

    return render(request,'accounts/rp_1.html',{'form':form})







def ChangePasswordView(request,slug):
    if request.method == 'POST':
        data = request.POST.copy()
        form = forms.ChangePasswordForm(data=request.POST)
        if form.is_valid():
            
            username = slug
            confirmation_code = data.get('confirmation_code')
            user = authenticate(request, username=username, password=confirmation_code)
             
            if user is not None:
                u = models.UserModel.objects.get(username__exact=username)
                password = data.get('new_password')

                try:
                    validate_password(password,user=u, password_validators=None)
                    u.set_password(password)               
                    u.save()
                    return redirect("accounts:success")
                except:
                    error1 ='کلمه عبور باید بیش از 6 کاراکتر باشد'
                    error2 ='کلمه عبور باید نمیتواند شامل نام کاربری باشد'
                    error3 ='کلمه عبور نمیتواند خیلی ساده باشد'
                    return render(request,'accounts/rp_2.html',{'form':form,'error1':error1,'error2':error2,'error3':error3})


            else:
                error = 'کد بازیابی وارد شده صحیح نمیباشد'
                return render(request,'accounts/rp_2.html',{'form':form,'error':error})
    else:
        form = forms.ChangePasswordForm()

    return render(request,'accounts/rp_2.html',{'form':form})






class SuccessView(TemplateView):

    template_name = 'accounts/rp_success.html'

accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
{% block head_block %}
{% endblock %}

    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no" />
    <link rel="stylesheet" href="{% static "assets/css/materialize.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/customize.css" %}">


</head>
<body>
{% block body_block %}

{% endblock %}
    <script src="{% static "assets/js/bin/anime.min.js" %}"> </script>
    <script src="{% static "assets/js/datepicker.js" %}"> </script>
    <script>
        M.AutoInit();

    </script>
</body>
</html>

accounts/templates/accounts/change_password.html
{% extends "accounts/base.html" %}


{% block head_block %}

{% endblock %}


{% block body_block %}

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    
    <input type="submit" value="submit" />
</form>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}


{% block head_block %}
<title>
    ورود | سامانه جامع استارت آپ
</title>
{% endblock %}


{% block body_block %}

<form method="POST">
    {% csrf_token %}
    <div class="row main-panel">
        <div class="card col s12 m12 l8 offset-l2 xl4 offset-xl4 hoverable scale">
            <div class="section center-align">
                <h5>
                    ورود به حساب کاربری
                </h5>
            </div>
            <div class="divider"></div>
            <div class="section">
                <div class="input-field col s12 m12 l6 xl6">
                    {{form.username}}
                    <label for="username">نام کاربری</label>
                </div>
                <div class="input-field col s12 m12 l6 xl6">
                    {{form.password}}
                    <label for="password">کلمه عبور</label>
                </div>
            </div>
            <div class="section">
                <div class="row center-align">
                    <div class="col s10 m4 l4 xl4 offset-s1 push-xl8 push-l8 push-m8" style="padding: 5px 0px">
                        <button class="btn waves-effect waves-light  indigo" type="submit" name="action">
                            ورود
                            <i class="material-icons right">chevron_right</i>
                        </button>
                    </div>
                    <div class="col s10 m4 l4 xl4 offset-s1 pull-xl4 pull-l4 pull-m4" style="padding: 5px 0px">
                        <a href="{% url "accounts:forgot_password" %}" class="btn-flat waves-effect">فراموشی کلمه عبور</a>

                    </div>
                    <div class="col s10 m4 l4 xl4 offset-s1 pull-xl4 pull-l4 pull-m4" style="padding: 5px 0px">

                        <a href="{% url "accounts:signup" %}" class="btn-flat waves-effect">ایجاد حساب کاربری</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

{% endblock %}

accounts/templates/accounts/rp_1.html
{% extends "accounts/base.html" %}

{% block head_block %}
<title>
    فراموشی کلمه عبور | سامانه جامع استارت آپ
</title>
{% endblock %}

{% block body_block %}

<form method="POST">
    {% csrf_token %}
    <div class="row main-panel">
        <div class="card col s12 m12 l8 offset-l2 xl4 offset-xl4 hoverable scale">
            <div class="section center-align">
                <h5>
                    فراموشی کلمه عبور
                </h5>
            </div>
            <div class="divider"></div>
            <div class="section">
                <div class="input-field col s12 m12 l6 xl6">
                    {{form.username}}
                    <label for="username">نام کاربری</label>
                </div>
                {{error}}
            </div>
            <div class="col s10 m10 l4 xl4 offset-s1 offset-m1 offset-l1 offset-xl1" style="padding: 5px 0px">
                <button class="btn waves-effect waves-light  indigo" type="submit" name="action">
                    ارسال کد بازیابی
                    <i class="material-icons right">chevron_right</i>
                </button>
            </div>

        </div>
    </div>
</form>

{% endblock %}

accounts/templates/accounts/rp_2.html
{% extends "accounts/base.html" %}

{% block head_block %}
<title>
    فراموشی کلمه عبور | سامانه جامع استارت آپ
</title>
{% endblock %}

{% block body_block %}

<form method="POST">
    {% csrf_token %}
    <div class="row main-panel">
        <div class="card col s12 m12 l8 offset-l2 xl4 offset-xl4 hoverable scale">
            <div class="section center-align">
                <h5>
                    تغییر کلمه عبور
                </h5>
            </div>
            <div class="divider"></div>
            <div class="section">
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.confirmation_code}}
                    <label for="password">کد بازیابی</label>
                    {% if error %}
                    <span class="helper-text" data-error="wrong" data-success="right">{{error}}</span>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l6 xl6">
                    {{form.new_password}}

                    {% if error1 %}
                    <span class="helper-text" data-error="wrong" data-success="right">
                        {{error1}}<br />
                        {{error2}}<br />
                        {{error3}}<br />
                    </span>
                    
                    {% endif %}


                    <label for="password">کلمه عبور جدید</label>
                </div>
                <div class="input-field col s12 m12 l6 xl6">
                    {{form.new_password_confirm}}
                    <label for="password_r">تکرار کلمه عبور</label>
                    {% if form.errors %}
                    <span class="helper-text" data-error="wrong" data-success="right">کلمات عبور هم خوانی ندارد</span>
                    {% endif %}
                </div>
            </div>
            

            

            <div class="col s10 m10 l10 xl10 offset-s1 offset-m1 offset-l1 offset-xl1" style="padding: 5px 0px">
                <button class="btn waves-effect waves-light  indigo" type="submit" name="action" style="width: 100%; margin: 20px;">
                    تغییر کلمه عبور
                    <i class="material-icons right">chevron_right</i>
                </button>
            </div>

        </div>
    </div>
</form>
{% endblock %}

accounts/templates/accounts/rp_success.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <title>
        فراموشی کلمه عبور | سامانه جامع استارت آپ
    </title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0,target-densitydpi=device-dpi, user-scalable=no" />
    <link rel="stylesheet" href="{% static "assets/css/materialize.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/style.css" %}">
    <link rel="stylesheet" href="{% static "assets/css/customize.css" %}">
</head>
<body>
    <div class="success-message green accent-1 blue-grey-text">
        تغییر کلمه عبور با موفقیت انجام شد
        <br>
        <a class="btn waves-effect waves-light" href="{% url "accounts:login" %}" style="margin: 20px;">
            ورود به حساب
        </a>
    </div>


    <script src="{% static "assets/js/bin/anime.min.js" %}">></script>
    <script>
        M.AutoInit();

    </script>
</body>
</html>

accounts/templates/accounts/rp_success2.html
{% extends "accounts/base.html" %}

{% block head_block %}
<title>
    فراموشی کلمه عبور | سامانه جامع استارت آپ
</title>
{% endblock %}

{% block body_block %}


<div class="success-message green accent-1 blue-grey-text">
    تغییر کلمه عبور با موفقیت انجام شد
    <br>
    <a class="btn waves-effect waves-light" href="{% url "accounts:login" %}" style="margin: 20px;">
        ورود به حساب
    </a>
</div>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}

{% block head_block %}
<title>
    ثبت نام | سامانه جامع استارت آپ
</title>
{% endblock %}

{% block body_block %}

<form method="POST">
    {% csrf_token %}
    <div class="row main-panel 	main-panel-s">
        <div class="card col s12 m12 l8 offset-l2 xl4 offset-xl4 hoverable scale">
            <div class="section center-align scale-transition">
                <h5>
                    ایجاد حساب کاربری
                </h5>
            </div>
            <div class="divider"></div>
            <div class="section">
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.username}}
                    
                    <label for="username">نام کاربری</label>
                    {% if form.username.errors %}
                    <p>نام کاربری قبلا ثبت شده است</p>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.password1}}
                    <label for="password">کلمه عبور</label>
                    {% if form.password1.errors %}
                    <p>رمز عبور باید بیش از 6 کاراکتر باشد</p>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.password2}}
                    <label for="passwordRepeat">تکرار کلمه عبور</label>
                    {% if form.password2.errors %}
                    <p>تکرار رمز عبور مطابقت ندارد</p>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.email}}
                    <label for="mail">آدرس ایمیل</label>
                    {% if form.email.errors %}
                    <p>ایمیل وارد شده صحیح نمیباشد</p>
                    {% endif %}
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.Firstname}}
                    <label for="fname">نام</label>
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.Lastname}}
                    <label for="lname">نام خانوادگی</label>
                </div>
                <div class="input-field col s12 m12 l12 xl12">
                    {{form.Birth}}
                    <label for="birthday">تاریخ تولد</label>
                </div>
                <div class="input-field col s12 m12 l8 xl8">
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div class="g-recaptcha" data-sitekey="6LeTw4UUAAAAAOGwJYQ0lSh3UOrzbyI_c8jJ5WPm"></div>
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li>
                            {{ message }}
                        </li>
                            {% endfor %}
                    </ul>
                    {% endif %}

                </div>

                <p style="text-align: center">
                    <label>
                        {{form.terms}}
                        <span>شرایط و قوانین استفاده از سامانه را می پذیرم</span>
                    </label>
                </p>



            </div>
            <div class="section">
                <div class="row center-align">
                    <div class="col s10 m6 l6 xl6 offset-s1 push-xl5 push-l5 push-m5" style="padding: 5px 0px">
                        <button class="btn indigo waves-effect waves-light " type="submit" name="action">
                            ایجاد حساب
                            <i class="material-icons right">account_circle</i>
                        </button>
                    </div>
                    <div class="col s10 m6 l6 xl6 offset-s1 pull-xl5 pull-l5 pull-m5" style="padding: 5px 0px">
                        <a class="btn-flat waves-effect" href="{% url 'accounts:login' %}">
                            ورود با حساب موجود
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/index.html
{% extends "accounts/base.html" %}

{% block head_block %}
<title>
    خانه | سامانه جامع استارت آپ
</title>

{% endblock %}

{% block body_block %}

<h1>This is the main view</h1>
{% if user.is_authenticated %}
<h1><b>Welcome {{user.username}}</b></h1>
{% if user.details.Firstname == 'amir' %}
{{user.details.Firstname}}
this is working
{% endif %}
{% else %}
<p>click <a href="{% url 'accounts:login'%}">here</a> to go to login page</p>
{% endif %}

{% endblock %}